eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.99.101:8761/eureka/
server:
  port: 6565
  use-forward-headers: true
spring:
  application:
    name: turbine
zuul:
  sensitive-headers:
  strip-prefix: false
  ignore-security-headers: false
turbine:
  aggregator:
    clusterConfig: CLIENT
  appConfig: client

---
spring:
  profiles: docker_env
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

