spring:
  application:
    name: eventclient
  cloud:
    stream:
      bindings:
        output:
            destination:  eventtopic
            content-type: application/json
        input:
            destination:  eventtopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: 192.168.99.101
          brokers: 192.168.99.101
logging:
  level:
    org.springframework.kafka: trace
---
spring:
  profiles: docker_env
  application:
    name: eventclient
  cloud:
    stream:
      bindings:
        input:
            destination:  eventtopic
            content-type: application/json
        output:
            destination:  eventtopic
            content-type: application/json
      kafka:
        binder:
          zkNodes: ${ENV_HOST}
          brokers: ${ENV_HOST}
          