environment:
  host: ${ENV_HOST}

#logging:
#  level:
#    org.springframework: debug
  
server:
  port: 8888
spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
#          searchLocations: file://config/src/main/resources/clientconfig/client,
#                               file://config/src/main/resources/clientconfig/client-a,
#                               file://config/src/main/resources/clientconfig/client-b
          searchLocations: classpath:clientconfig/,classpath:clientconfig/client,classpath:clientconfig/client-a,classpath:clientconfig/client-b
    
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/PascalStieber/config-repo/
##         create a new repository 'config-repo' with a folder 'client' and put a 'client-a.yml' in it
##         may it makes sense to have differ .yml files for different profiles (e.g.: 'client-docker_env.yml')
#          searchPaths: client-a,client-b
#          username: myUsername
#          password: myPassword

---
#Classpath and file-based solution
spring:
  profiles: local_file_env
  cloud:
    config:
      server:
        native:
          searchLocations: file://config/src/main/resources/clientconfig/client-a,
                               file://config/src/main/resources/clientconfig/client-b
#             searchLocations: classpath:clientconfig/,classpath:clientconfig/client-a,classpath:clientconfig/client-b


---
spring:
  profiles: docker_env

