server:
  port: 9411
spring:
  application:
    name: zipkin
eureka:
  instance:
    prefer-ip-address: true
  client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker_env
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/