version: '3.4'
services:
  client:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env
      ENV_HOST: 192.168.99.101
    build: ./client
    #use image tag to specify concrete version. make sure to generated this version and change the <tag> property in dockerfile-maven-plugin 
    #image: springcommondemo_client:1.3.1-SNAPSHOT
    networks:
    - mynetwork
    ports:
    - 8080:8080    
    
networks:
  mynetwork:
    driver: bridge