version: '3'
services:
  eureka:
    build: ./eureka
    networks:
    - mynetwork
    ports:
    - 8761:8761
  oauth2:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env
      ENV_HOST: ${DOCKER_HOST}
    build: ./oauth2
    networks:
    - mynetwork
    ports:
    - 8585:8585
  zipkin:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env
      ENV_HOST: 192.168.99.101
    build: ./zipkin
    networks:
    - mynetwork
    ports:
    - 9411:9411
  config:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env,native
      ENV_HOST: 192.168.99.101
    build: ./config
    networks:
    - mynetwork
    ports:
    - 8888:8888
  zuul:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env
      ENV_HOST: 192.168.99.101
    build: ./zuul
    networks:
    - mynetwork
    ports:
    - 9999:9999
  client:
    environment:
      SPRING_PROFILES_ACTIVE: docker_env
      ENV_HOST: 192.168.99.101
    build: ./client
    networks:
    - mynetwork
    depends_on:
    - config
    - eureka
    - oauth2
    - zipkin
    - zuul
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - mynetwork
    environment:
      - MONGO_DATA_DIR=/data/mongodb
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/mongodb
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
      
networks:
  mynetwork:
    driver: bridge