eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
  use-forward-headers: true
spring:
  application:
    name: zuul
zuul: 
  sensitive-headers:
  ignore-security-headers: false
  add-proxy-headers: true
  add-host-header: true
  force-original-query-string-encoding: true
  routes:
    intro: 
      path: /
      service-id: client
      strip-prefix: true
    client:
      service-id: client
#      sensitive-headers:
      strip-prefix: false
    oauth2:
      service-id: oauth2
#      sensitive-headers:
      strip-prefix: false  

      
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: docker_env
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

