eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
  use-forward-headers: true
spring:
  application:
    name: zuul
zuul:
  sensitive-headers:
  strip-prefix: false
  ignore-security-headers: false
---
spring:
  profiles: docker_env
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

