spring:
  boot:
    admin:
      routes:
        endpoints:
        - env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
      
        
        
        