environment:
  host: ${ENV_HOST}
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.101:8761/eureka/
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: CLIENTSESSION

spring:
  kafka:
   consumer:
      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: eventtopic
      auto-offset-reset: earliest   
   bootstrap-servers:
   - http://192.168.99.101:9092
   producer:
    key-serializer:
      org.apache.kafka.common.serialization.StringSerializer
    value-serializer:
      org.springframework.kafka.support.serializer.JsonSerializer  
  cloud:
    stream:
      bindings:
        output:
            destination:  eventtopic
            content-type: application/json
        input:
            destination:  eventtopic
            content-type: application/json
      kafka:
        binder:
          brokers: 192.168.99.101
  zipkin:
    baseUrl:  http://192.168.99.101:9999/zipkin
  data:
    mongodb:
      host: 192.168.99.101
      port: 27017
  redis:
    host: 192.168.99.101
    port: 6379
---
spring:
  profiles: docker_env
  data:
    mongodb:
      host: ${ENV_HOST}
      port: 27017
  cloud:
    config:
      uri: http://${ENV_HOST}:9999/config
  zipkin:
    baseUrl:  http://${ENV_HOST}:9999/zipkin
  thymeleaf:
    cache: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      access-token-uri: http://${ENV_HOST}:8585/secret/oauth/token
      user-authorization-uri: http://${ENV_HOST}:8585/secret/oauth/authorize
    resource:
      user-info-uri: http://${ENV_HOST}:8585/secret/user/me
      jwt:
        key-uri: http://${ENV_HOST}:8585/secret/oauth/token_key