spring:
  application:
        name: oauth2
  data:
    mongodb:
      host: 192.168.99.101
      port: 27017
server:
    servlet:
      context-path: /oauth2
    port: 8585
    use-forward-headers: true
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
eureka:
  instance:
    prefer-ip-address: true
  client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: TRACE
---

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/

spring:
  security:
    user:
        password: password
  profiles: docker_env 
  data:
    mongodb:
      host: 192.168.99.101
      port: 27017

