spring:
    application:
        name: oauth2
server:
    contextPath: /secret
    port: 8585
    use-forward-headers: true
eureka:
  instance:
    prefer-ip-address: true
  client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: TRACE

---

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
security:
    user:
        password: password
spring:
  profiles: docker_env 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Cash##1989
    url: jdbc:mysql://192.168.178.20:3306/mrlocksmithmicroservices
    username: root
